import React from 'react';
import {
  GoogleDriveIcon,
  GmailIcon,
  GoogleCalendarIcon,
  GoogleDocsIcon,
  GoogleSheetsIcon,
  GoogleMeetIcon,
  GoogleFormsIcon,
  GoogleClassroomIcon,
  GoogleChatIcon,
  GoogleKeepIcon,
  GoogleSlidesIcon,
  GoogleTasksIcon,
  GooglePeopleIcon,
  GooglePhotosIcon,
  YouTubeIcon,
  NotionIcon,
  DiscordIcon,
  SlackIcon,
  CustomMCPIcon,
} from './MCPIcons';

export interface MCPService {
  id: string;
  name: string;
  category: 'google' | 'communication' | 'productivity' | 'custom';
  badge: string;
  color: string;
  glowColor: string;
  icon: React.ComponentType<{ className?: string; size?: number }>;
  description: string;
  mcpTools: string[];
  simulatedAction: {
    command: string;
    log: string;
    result: string;
  };
}

export const MCP_SERVICES: MCPService[] = [
  {
    id: 'gmail',
    name: 'Gmail',
    category: 'google',
    badge: 'Email & Triage',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: GmailIcon,
    description: 'Triage inbox, draft replies, search priority threads, and parse attachments autonomously.',
    mcpTools: ['gmail_list_threads', 'gmail_send_draft', 'gmail_search_messages'],
    simulatedAction: {
      command: 'meridius.mcp.gmail.triage_unread({ filter: "is:priority" })',
      log: 'Triaging 14 unread priority threads & preparing draft responses...',
      result: 'Drafted 3 replies, flagged 2 invoice confirmations, 0 screen clicks needed',
    },
  },
  {
    id: 'google-calendar',
    name: 'Calendar',
    category: 'google',
    badge: 'Schedule & Time',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: GoogleCalendarIcon,
    description: 'Check team availability, resolve scheduling conflicts, and create events in parallel.',
    mcpTools: ['calendar_list_events', 'calendar_create_event', 'calendar_freebusy'],
    simulatedAction: {
      command: 'meridius.mcp.calendar.schedule_sync({ title: "Product Roadmap", duration: "45m" })',
      log: 'Analyzing attendee timezones and finding overlapping free slot...',
      result: 'Scheduled for Friday 11:00 AM PST · Sent invites with Google Meet link',
    },
  },
  {
    id: 'google-drive',
    name: 'Drive',
    category: 'google',
    badge: 'Cloud Storage',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: GoogleDriveIcon,
    description: 'Index documents, search files, manage permissions, and stream content into agent context.',
    mcpTools: ['drive_search_files', 'drive_read_metadata', 'drive_download_file'],
    simulatedAction: {
      command: 'meridius.mcp.drive.search({ query: "name contains \'Q3 Financials\'" })',
      log: 'Located "Q3 Financial Projections.pdf" and extracted financial tables...',
      result: 'Synthesized 4 key revenue delta points into working memory',
    },
  },
  {
    id: 'google-docs',
    name: 'Docs',
    category: 'google',
    badge: 'Documents & Writing',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: GoogleDocsIcon,
    description: 'Read specifications, append research findings, and format release documentation.',
    mcpTools: ['docs_get_document', 'docs_batch_update', 'docs_insert_text'],
    simulatedAction: {
      command: 'meridius.mcp.docs.append_notes({ docId: "spec_v2_4", section: "Security" })',
      log: 'Appending zero-screen hardware isolation proof to Architecture Spec...',
      result: 'Successfully updated Document (v2.4) with formatted markdown sections',
    },
  },
  {
    id: 'google-sheets',
    name: 'Sheets',
    category: 'google',
    badge: 'Data & Analytics',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: GoogleSheetsIcon,
    description: 'Query spreadsheets, compute multi-column aggregations, and update metrics live.',
    mcpTools: ['sheets_get_values', 'sheets_append_rows', 'sheets_batch_calculate'],
    simulatedAction: {
      command: 'meridius.mcp.sheets.query({ sheet: "Waitlist_Telemetry", range: "A1:G500" })',
      log: 'Calculating weekly cohort retention and conversion rates...',
      result: 'Calculated 91.4% retention delta · Appended metrics row to Column H',
    },
  },
  {
    id: 'google-meet',
    name: 'Meet',
    category: 'google',
    badge: 'Video & Audio',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: GoogleMeetIcon,
    description: 'Generate instant bridges, sync call agendas, and capture audio transcripts seamlessly.',
    mcpTools: ['meet_create_space', 'meet_get_conference', 'meet_list_participants'],
    simulatedAction: {
      command: 'meridius.mcp.meet.create_space({ topic: "Meridius Sync Standup" })',
      log: 'Created dynamic room space with end-to-end encryption...',
      result: 'Room ready at meet.google.com/xyz-core · Synced to event attendees',
    },
  },
  {
    id: 'google-forms',
    name: 'Forms',
    category: 'google',
    badge: 'Surveys & Feedback',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: GoogleFormsIcon,
    description: 'Stream survey submissions, analyze customer sentiment, and summarize responses.',
    mcpTools: ['forms_get_form', 'forms_list_responses', 'forms_watch_submissions'],
    simulatedAction: {
      command: 'meridius.mcp.forms.aggregate_feedback({ formId: "beta_testing_2026" })',
      log: 'Fetched 58 user test submissions and grouped recurring bug requests...',
      result: '91% cited "zero cursor takeover" as their #1 loved feature',
    },
  },
  {
    id: 'google-classroom',
    name: 'Classroom',
    category: 'google',
    badge: 'Education & Courses',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: GoogleClassroomIcon,
    description: 'Sync course rosters, retrieve student assignment submissions, and track grades.',
    mcpTools: ['classroom_list_courses', 'classroom_list_submissions', 'classroom_grade'],
    simulatedAction: {
      command: 'meridius.mcp.classroom.sync_assignments({ courseId: "cs_systems_401" })',
      log: 'Scanning pending lab submissions for Operating Systems course...',
      result: 'Organized 42 student test results into local grading matrix',
    },
  },
  {
    id: 'google-chat',
    name: 'Chat',
    category: 'google',
    badge: 'Team Messaging',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: GoogleChatIcon,
    description: 'Send automated alerts, listen to thread mentions, and post markdown reports.',
    mcpTools: ['chat_create_message', 'chat_list_spaces', 'chat_stream_events'],
    simulatedAction: {
      command: 'meridius.mcp.chat.post_message({ space: "eng_core", text: "Build Passed" })',
      log: 'Broadcasting automated CI/CD pipeline verification to Chat space...',
      result: 'Message posted with rich card payload and build artifacts link',
    },
  },
  {
    id: 'google-keep',
    name: 'Keep',
    category: 'google',
    badge: 'Quick Notes',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: GoogleKeepIcon,
    description: 'Create pinned scratchpads, fetch voice notes, and manage checklist items.',
    mcpTools: ['keep_list_notes', 'keep_create_note', 'keep_update_checkboxes'],
    simulatedAction: {
      command: 'meridius.mcp.keep.create_note({ title: "YC SF Founder Prep", items: 5 })',
      log: 'Creating checklist note with synchronized background status...',
      result: 'Note created & pinned: "Himel Hasan — Meridius CEO Brief"',
    },
  },
  {
    id: 'google-slides',
    name: 'Slides',
    category: 'google',
    badge: 'Presentations',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: GoogleSlidesIcon,
    description: 'Generate presentation layouts, update slide metrics, and align design elements.',
    mcpTools: ['slides_get_presentation', 'slides_create_slide', 'slides_replace_all_text'],
    simulatedAction: {
      command: 'meridius.mcp.slides.update_metrics({ deckId: "seed_pitch_deck" })',
      log: 'Replacing placeholder growth charts with verified Supabase telemetry...',
      result: 'Updated 6 slide metric callouts in 1.4 seconds',
    },
  },
  {
    id: 'google-tasks',
    name: 'Tasks',
    category: 'google',
    badge: 'Task Management',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: GoogleTasksIcon,
    description: 'Sync todos, prioritize action items, and auto-complete finished agent jobs.',
    mcpTools: ['tasks_list_tasks', 'tasks_insert_task', 'tasks_complete_task'],
    simulatedAction: {
      command: 'meridius.mcp.tasks.complete_batch({ ids: ["build_mcp_section", "test_svg"] })',
      log: 'Marking completed engineering milestones in Tasks hierarchy...',
      result: '2 tasks resolved · Reordered backlog by execution priority',
    },
  },
  {
    id: 'google-people',
    name: 'Contacts',
    category: 'google',
    badge: 'Contacts & Directory',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: GooglePeopleIcon,
    description: 'Look up directory contacts, manage connection groups, and enrich profile metadata.',
    mcpTools: ['people_search_contacts', 'people_get_profile', 'people_update_metadata'],
    simulatedAction: {
      command: 'meridius.mcp.people.search({ name: "Himel Hasan" })',
      log: 'Resolving contact profile and recent communication history...',
      result: 'Contact card linked with founder email & calendar schedule',
    },
  },
  {
    id: 'google-photos',
    name: 'Photos',
    category: 'google',
    badge: 'Media & Visuals',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: GooglePhotosIcon,
    description: 'Organize screenshots, retrieve product visuals, and index visual memories.',
    mcpTools: ['photos_search_media', 'photos_create_album', 'photos_batch_tag'],
    simulatedAction: {
      command: 'meridius.mcp.photos.search({ query: "Meridius macOS UI screenshot" })',
      log: 'Searching photo library with visual embedding query...',
      result: 'Retrieved 8 high-res app screenshots from local photo cache',
    },
  },
  {
    id: 'youtube',
    name: 'YouTube',
    category: 'google',
    badge: 'Video & Transcripts',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: YouTubeIcon,
    description: 'Fetch video captions, parse video timestamps, and summarize technical demos.',
    mcpTools: ['youtube_get_transcript', 'youtube_search_videos', 'youtube_parse_chapters'],
    simulatedAction: {
      command: 'meridius.mcp.youtube.get_transcript({ videoId: "meridius_demo_1080p" })',
      log: 'Downloading timed captions and chapter markers...',
      result: 'Generated 5-bullet summary of founder product walk-through',
    },
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'productivity',
    badge: 'Workspace & Docs',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: NotionIcon,
    description: 'Query company databases, create sprint tickets, and synchronize team knowledge.',
    mcpTools: ['notion_query_database', 'notion_create_page', 'notion_update_block'],
    simulatedAction: {
      command: 'meridius.mcp.notion.create_page({ parentDb: "Engineering_Sprint", title: "MCP Integration" })',
      log: 'Generating Notion page with structured schema & acceptance criteria...',
      result: 'Created page in Sprint Backlog with bidirectional links',
    },
  },
  {
    id: 'discord',
    name: 'Discord',
    category: 'communication',
    badge: 'Community & Voice',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: DiscordIcon,
    description: 'Monitor community channels, dispatch notifications, and interact with developer bots.',
    mcpTools: ['discord_send_message', 'discord_read_channel', 'discord_listen_events'],
    simulatedAction: {
      command: 'meridius.mcp.discord.post_embed({ channel: "announcements", title: "MCP Support Live" })',
      log: 'Dispatching rich embed message to Discord developer server...',
      result: 'Broadcasted to 1,240 community members with live feedback bot',
    },
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'communication',
    badge: 'Enterprise Chat',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.15)',
    icon: SlackIcon,
    description: 'Coordinate across workspaces, synthesize threads, and automate team workflows.',
    mcpTools: ['slack_post_message', 'slack_get_conversation_replies', 'slack_set_status'],
    simulatedAction: {
      command: 'meridius.mcp.slack.summarize_thread({ channel: "#leadership", threadTs: "1724500.12" })',
      log: 'Reading 26 thread messages and extracting action item decisions...',
      result: 'Posted 3-bullet executive brief directly into channel',
    },
  },
  {
    id: 'custom-mcp',
    name: 'Custom MCP',
    category: 'custom',
    badge: 'Extensible Protocol',
    color: '#5B8CFF',
    glowColor: 'rgba(91, 140, 255, 0.25)',
    icon: CustomMCPIcon,
    description: 'Connect any custom stdio, HTTP SSE, or internal Model Context Protocol server.',
    mcpTools: ['mcp_connect_stdio', 'mcp_connect_sse', 'mcp_discover_tools'],
    simulatedAction: {
      command: 'meridius.mcp.connect({ transport: "stdio", command: "npx my-custom-mcp-server" })',
      log: 'Discovering 12 custom schemas, prompt templates, and tool primitives...',
      result: 'Connected in 8ms · Seamlessly accessible to Meridius agent loop',
    },
  },
];
